### ISSUE TITLE
Sort order items in category

### ISSUE THREAD

**Issue by Uzenmi** [gocart/GoCart3#18]
It has an error while I selected to reorder items in category. Ex, Sort by name A to Z; Z  to A.

And product images can not upload.

**Comment by gocart** [comment]
couple questions.
1. what version are you running (check the version file in your root directory).
2. Check to ensure the permissions on your upload directory are correct.

**Comment by Uzenmi** [comment]
1. I installed on Gocart version 3 (release date 2015.08.12).
2. I checked and images can be uploaded. But images files are not deleted from server when I deleted in Admin control panel.

And it's error "404" while I try to sort list items in category on the front page, that error like on your [demo](https://demo.gocartdv.com/G9YS313/category/tablets/?by=name/desc).

**Comment by Uzenmi** [comment]
Hello?

**Comment by gocart** [comment]
1. is fixed with https://github.com/gocart/GoCart3/commit/1f392b71560fe3efac224cf6dc823e5266ee42ee
2. Is not going to be changed any time soon. With the copy product feature it's possible that a product image could be shared between multiple products. This could lead to broken images if images are deleted with a product. We may change the way images are associated with products one day but it's not high on the priority list.

**Comment by Uzenmi** [comment]
I really don't need the copy product feature for my website and I don't want to see the excess image files on the server. So can you please help me how to do that? Many thanks.

**Comment by gocart** [comment]
If you require assistance with GoCart customizations I would suggest you use the contact form on the website @ https://gocartdv.com/page/customization to request commercial support.
