### ISSUE TITLE
Gumbo

### ISSUE THREAD

**Issue by olimortimer** [gocart/GoCart3#2]
Is Gumbo something created by Clear Sky Designs, or a third party framework?  Is there any reason that was used for the front-end, rather than re-using Bootstrap which is used in the admin?

**Comment by gocart** [comment]
Hey Oli. I wrote gumbo outside of Clear Sky Designs for myself, but ultimately used it for all the designs I do. I wanted to use it for the Admin side as well but couldn't fit it in for this initial build.

Aside from the quick admin update I quit using bootstrap due to the fact that so much changes between versions and it does not support multi-tiered drop downs.

All that said a theme could be written on whatever framework anyone wants to build on pretty easily.

**Comment by olimortimer** [comment]
Thanks for the info :) Just playing around with GoCart3 (didn't even know it had been created!), so finding all the new things that have been added and changed etc.

**Comment by gocart** [comment]
No problem, I look forward to seeing what you think of the system. We have documentation now too!

**Comment by olimortimer** [comment]
Just spotted that :)

My first concern when firing it all up, was the change to order addresses so they are no longer saved as a full address against the order, but linked to the address table instead - I was worried that changing an address after an order was placed, would also change the address against the order (something we found in some old e-commerce software we were using at work), but thankfully this doesn't seem to be the case!

Will there be an importer for GoCart3, to import data from a GoCart2 shop?

**Comment by gocart** [comment]
Yeah I bumped into that problem the day I made that shift with the addresses. Currently there is not a migration script. We've done some internal work for our own shop but not anything we would be comfortable distributing yet. I'm not entirely sure there would be a big demand for it considering how many people customized their GoCart installations and probably wouldn't want to go through the work of reimplementing their changes.

I'm sure it would be relatively simple to do some importing though even if it's not the whole database.
